apiVersion: v1
kind: Pod
metadata:
  namespace : sock-shop
  name: locust
spec:
  containers:
  - name: locust
    image: alex7285/locust@sha256:571a87b4ad39f93e87721a3477423d6714143c21b433967b55132ae2d9d46a75
    env: 
      - name : FRONT_END_URL
        value : "http://front-end:80"